-- +goose Up
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_muted    BOOLEAN      NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS muted_until TIMESTAMPTZ;

-- +goose Down
ALTER TABLE users DROP COLUMN IF EXISTS muted_until;
ALTER TABLE users DROP COLUMN IF EXISTS is_muted;
